apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-aag-cluster
  region: us-east-2
  version: "1.24"
availabilityZones: ["us-east-2a", "us-east-2b"]
managedNodeGroups:
- name: mynodegroup
  desiredCapacity: 2
  instanceType: t2.micro
  ssh:
    enableSsm: true
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoscaler: true
      externalDNS: true
      certManager: true
      ebs: true
      albIngress: true
      xRay: true
iam:
  withOIDC: true
secretsEncryption:
  keyARN: arn:aws:kms:us-east-2:514132458783:key/d56cbfca-60fa-490e-b1bc-9ba1004e0430
