apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: eu-west-2
  version: "1.24"
availabilityZones: ["eu-west-2a", "eu-west-2b"]
managedNodeGroups:
- name: mynodegroup
  desiredCapacity: 2
  instanceType: t2.micro
  ssh:
    enableSsm: true
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoscaler: true
      externalDNS: true
      certManager: true
      ebs: true
      albIngress: true
      xRay: true
iam:
  withOIDC: true
karpenter:
  version: '0.21.1'
secretsEncryption:
  keyARN: ${MASTER_ARN}